version: "2"

services:
  app:
    image: simplycodedsoftware/ci:7.1
    container_name: "integration-messaging-app"
    volumes:
      - "$PWD:/data/app"
      - "$HOME/.ssh:/home/deploy/.ssh"
    user: 1000:1000
    working_dir: "/data/app"
    command: sleep 99999
    networks:
      - default
    ports:
      - "3000:80"

networks:
  default:
    driver: bridge